### PR TITLE
INCR transfer bug fixes

### PR DESCRIPTION
**Pull request by ebiggers**

### CODE REVIEW

**Comment by wsdjeg** [comment]
@ebiggers I am not sure this patch will be merged, but I need this featue in neovim. as the issue opened here
https://github.com/neovim/neovim/issues/4719
before it is merged, I am using xclip.

**Comment by justinmk** [comment]
@kfish can you comment?

**Comment by MaskRay** [comment]
In Arch Linux, the following script can mitigate the bug ( community/xsel-1.2.0-6 )

```zsh
# zsh
xxd =xsel | sed -r 's/(00003930: .*)0f 8f9a 0000 00/\19090 9090 9090/' | xxd -r > /tmp/x && sudo cp /tmp/x =xsel
```

**Comment by AKurilin** [comment]
Thank you for fixing this, @ebiggers .

**Pull request merged**
